Выполнено домашнее задание 5
MrPelmenik/HW-Directum pull request #1
Opened 2024-09-17 21:15 UTC by MrPelmenik

Сталкер и доктор

Сталкер пришел к доктору и говорит:

— Доктор, я совсем не могу спать… Мне снится, будто я заперт в саркофаге… с кучей монстров, и они медленно разрывают меня на кусочки.

— Это Вас, уважаемый, контролёр предупреждает. Рецепт мой такой: в следующий раз пойдете вглубь зоны, обязательно бутылку ему проставьте. А то, неровен час, сон в явь превратится.

— Ну, спасибо Вам большое, доктор.

— Да не за что! — говорит контролёр, — это тебе за доктора спасибо. Мелочь, а приятно…

2024-09-18 19:14 UTC, Dezodemius requested changes

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +    internal interface IWorker // Сделаем рабочего и офисника
Документация нужная для интерфейса и всех его членов

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        string name { get; set; }
Документация нужна

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        string workPlace { get; }
По соглашению о кодировании свойства мы должны писать с большой буквы

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        int salary { get; set; }
Между членами класса нужны переносы строк. Вообще везде нужны переносы строк (члены класса, классы, регионы, и между кусками кода, которые работают над чем-то одним)

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/TeamOperation.cs
> +    public class TeamOperation
Документация нужна

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/TeamOperation.cs
> +            Console.Write("Input name: ");
Давай уберём из этого класса Console.Write и тд. Пусть письмо в консоль будет за классом Program

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/TeamOperation.cs
> +            int salary = int.Parse(Console.ReadLine());
И вообще вся работа с консолью через класс Program. Запрос у пользователя тоже там должен быть

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/Worker.cs
> +
Лишний отступ

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/Worker.cs
> +    public class ProductWorker : IWorker
Нужно вынести в отдельный класс

2024-09-18 19:14 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/Worker.cs
> +        public ProductWorker(string name, int salary)
Коль тут ещё и конструктор помимо свойств есть, то нужно регионы добавить

2024-09-20 15:26 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/Worker.cs
> +
Исправил

2024-09-20 15:28 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/Worker.cs
> +    public class ProductWorker : IWorker
Исправил

2024-09-20 15:32 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/Worker.cs
> +        public ProductWorker(string name, int salary)
Исправил

2024-09-20 15:40 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        string workPlace { get; }
Исправил

2024-09-20 15:46 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        string name { get; set; }
Исправил

2024-09-20 15:46 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +    internal interface IWorker // Сделаем рабочего и офисника
Исправил

2024-09-20 15:46 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        int salary { get; set; }
Исправил

2024-09-20 16:52 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/TeamOperation.cs
> +            Console.Write("Input name: ");
Исправил

2024-09-21 12:19 UTC, Dezodemius commented
Добавь в корень всего репозитория файл `.gitignore`. Вставь туда содержимое из [файла](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore).
Затем на компе в консоли из папки с этим же репозиторием выполни команду `git rm -r -q --cached .` и запуш сюда

2024-09-22 17:25 UTC, Dezodemius requested changes

2024-09-22 17:25 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +    internal interface IWorker // Сделаем рабочего и офисника
Лишний коммент

2024-09-22 17:25 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        /// Имя
Нужно точки расставить везде в доках

2024-09-22 17:25 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +    /// Интерфейс работяга
Просто `Работяга`

2024-09-22 17:25 UTC, Dezodemius commented on HWForCountingPeople/WorkerFolder/OfficeWorker.cs
> +        public string Name { get; set; }
Это же свойства из интерфейса. Их нужно в регион с именем `IWroker` перенести

2024-09-22 19:58 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +    internal interface IWorker // Сделаем рабочего и офисника
Исправил

2024-09-22 20:01 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +        /// Имя
Исправил

2024-09-22 20:01 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/IWorker.cs
> +    /// Интерфейс работяга
Исправил

2024-09-22 20:17 UTC, MrPelmenik commented on HWForCountingPeople/WorkerFolder/OfficeWorker.cs
> +        public string Name { get; set; }
Исправил

2024-09-23 19:31 UTC, Dezodemius approved these changes

2024-09-23 19:32 UTC, merged