Залил домашку-5
MrPelmenik/HW-Directum pull request #2
Opened 2024-09-25 20:34 UTC by MrPelmenik

Заходит парень в бар вместе с любимой обезьянкой.
Он заказывает выпивку, обезьяна начинает носится по бару.
К тому времени, как парень заканчивает пить, обезьяна находит на стойке вишни.
Она берет одну, пихает в задницу, вытаскивает и ест.
Бармен, чувствуя отвращение, обращается к хозяину
— Вы видели что ваша обезьяна вытворяет?
— А что?
— Она засовывает вишню в задницу, вытягивает и жрет!— Говорит бармен.
— Ничего удивительного,— отвечает парень.
— Она жрет все что попадается на глаза, но с тех пор, как сожрала бильярдный шар, предварительно все меряет….

2024-09-28 16:06 UTC, Dezodemius requested changes

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +    /// Операции с классом Person.
PeopleManager, кажется, лучше

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +    /// Операции с классом Person.
И в доке `Менеджер людей`

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +        List<Person> persons;
private. И дока нужна

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +        public PersonsOperations ()
дока. В регион `Конструкторы`, и в самый низ файла переместить

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +        public string AddPerson(string name)
не. Не нужно возвращать строку. Пусть метод будет void. Он должен только пытаться добавить новый объект в коллекцию, и, если такой там уже есть, то выбросить исключение

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +        public string AddPerson(string name)
в других методах так же. Мы добавим себе больше геморроя, если будем возвращать везде строки с объяснением, что произошло

2024-09-28 16:06 UTC, Dezodemius commented on HW-With-Exeption/PersonsOperations.cs
> +        public void ShowInfo()
пусть метод вернёт строку, а не будет сам её распечатывать в консоль

2024-09-30 19:55 UTC, MrPelmenik commented on HW-With-Exeption/PersonsOperations.cs
> +    /// Операции с классом Person.
Исправил

2024-09-30 19:58 UTC, MrPelmenik commented on HW-With-Exeption/PersonsOperations.cs
> +        List<Person> persons;
Исправил

2024-09-30 20:00 UTC, MrPelmenik commented on HW-With-Exeption/PersonsOperations.cs
> +        public PersonsOperations ()
Исправил

2024-09-30 20:01 UTC, MrPelmenik commented on HW-With-Exeption/PersonsOperations.cs
> +        public void ShowInfo()
Исправил

2024-09-30 20:15 UTC, Dezodemius approved these changes

2024-09-30 20:57 UTC, MrPelmenik commented on HW-With-Exeption/PersonsOperations.cs
> +        public string AddPerson(string name)
Исправил

2024-09-30 21:03 UTC, merged